services:
  mongo_db:
    image: mongo:4.4
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"  # HTTPS port
    volumes:
      - ./ssl:/app/ssl
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo_db
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: